# Generated by Django 5.2.1 on 2026-03-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('affiliate_link', models.URLField()),
                ('price', models.CharField(blank=True, max_length=50)),
                ('rating', models.FloatField(default=0)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Buy Now', max_length=50)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Home.post')),
            ],
        ),
    ]
