# Generated by Django 5.2.1 on 2025-07-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
