# Generated by Django 5.2.1 on 2025-07-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_leftpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
