# Generated by Django 5.2.1 on 2025-07-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rightpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftpost',
            name='slug',
            field=models.CharField(default=14, max_length=130),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rightpost',
            name='slug',
            field=models.CharField(default=0, max_length=130),
            preserve_default=False,
        ),
    ]
