# Generated by Django 5.2.1 on 2025-07-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_leftpost_slug_rightpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leftpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
