# Generated by Django 5.2.1 on 2025-07-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_alter_leftpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leftpost',
            name='slug',
        ),
    ]
