# Generated by Django 5.2.1 on 2025-07-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_leftpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftpost',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
